services:

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile

    container_name: healthify_backend

    working_dir: /var/www

    volumes:
      - ./BACKEND:/var/www

    ports:
      - "8000:8000"

    depends_on:
      - mysql

    command: php artisan serve --host=0.0.0.0 --port=8000

  web:
    build:
      context: ./WEB
      dockerfile: Dockerfile

    container_name: healthify_web

    working_dir: /app

    volumes:
      - ./WEB:/app

    ports:
      - "5173:5173"

    command: npm run dev -- --host

  mysql:
    image: mysql:8.0

    container_name: healthify_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pbl_backend_db

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: