import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter/services.dart';
// import 'pdf_chart_service.dart';

class PdfService {


  static Future<void> generateWeeklyReport(

    

    Map<String,dynamic>? user,

    Map<String,dynamic>? report,

    List<dynamic> foodHistory,

    List<dynamic> topFoods,

    List<dynamic> weightHistory,

    Map<String,dynamic>? coaching,

    Map<String,dynamic>? latestScreening,
) async {

    final pdf = pw.Document();
final ByteData imageData =
    await rootBundle.load(
      'assets/images/logo.png',
    );

final Uint8List imageBytes =
    imageData.buffer.asUint8List();

final logo = pw.MemoryImage(
  imageBytes,
);
    pdf.addPage(

      pw.MultiPage(

        pageFormat: PdfPageFormat.a4,

        build: (context) => [
pw.Center(
  child: pw.Column(
    children: [

      pw.SizedBox(height: 60),

      pw.Text(
        "HEALTHIFY",
        style: pw.TextStyle(
          fontSize: 34,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.teal,
        ),
      ),

      pw.SizedBox(height: 15),

      pw.Text(
        "Weekly AI Health Report",
        style: pw.TextStyle(
          fontSize: 20,
        ),
      ),

      pw.SizedBox(height: 40),

      pw.Text(
        "Prepared For",
      ),

      pw.SizedBox(height: 10),

      pw.Text(
        "${user?['name']}",
        style: pw.TextStyle(
          fontSize: 24,
          fontWeight: pw.FontWeight.bold,
        ),
      ),

      pw.SizedBox(height: 30),

      pw.Text(
        "Generated by Healthify AI",
      ),

      pw.SizedBox(height: 10),

      pw.Text(
        DateTime.now().toString(),
      ),

    ],
  ),
),

pw.NewPage(),
          // HEADER
pw.Center(

  child: pw.Column(

    children: [

      pw.Image(

        logo,

        width: 80,

        height: 80,

      ),

      pw.SizedBox(height:10),

      pw.Text(

        "HEALTHIFY",

        style: pw.TextStyle(

          fontSize: 28,

          fontWeight: pw.FontWeight.bold,

          color: PdfColors.teal,

        ),

      ),

      pw.Text(

        "Weekly AI Health Report",

        style: pw.TextStyle(

          fontSize: 18,

        ),

      ),
                pw.SizedBox(height:20),

                pw.Container(

                  padding: const pw.EdgeInsets.all(15),

                  decoration: pw.BoxDecoration(
                    color: PdfColors.teal50,
                    borderRadius: pw.BorderRadius.circular(10),
                  ),

                  child: pw.Column(

                    crossAxisAlignment: pw.CrossAxisAlignment.start,

                    children: [

                      pw.Text(
                        "Nama : ${user?['name']}",
                      ),

                      pw.Text(
                        "Email : ${user?['email']}",
                      ),

                      pw.Text(
                        "Usia : ${user?['age'] ?? '-'} tahun",
                      ),

                      pw.Text(
                        "Gender : ${latestScreening?['gender']}",
                      ),

                    ],

                  ),

                ),

              ],
            ),
          ),

          pw.Divider(),

          pw.SizedBox(height: 20),

          // SUMMARY
          pw.Text(
            "Summary",
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 10),

          pw.Container(

            padding: const pw.EdgeInsets.all(20),

            decoration: pw.BoxDecoration(

              color: PdfColors.blue50,

              borderRadius: pw.BorderRadius.circular(15),

              border: pw.Border.all(
                color: PdfColors.blue200,
              ),

            ),

            child: pw.Column(

              crossAxisAlignment:
                  pw.CrossAxisAlignment.start,

              children: [

                pw.Text(
                  "Health Summary",
                  style: pw.TextStyle(
                    fontSize: 20,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),

                pw.SizedBox(height: 20),

                pw.Text(
                  "BMI : ${latestScreening?['imt_value']}",
                ),

                pw.Text(
                  "Status BMI : ${latestScreening?['imt_classification']}",
                ),

                pw.Text(
                  "Risk Level : ${latestScreening?['risk_level']}",
                ),
pw.SizedBox(height:15),

pw.Container(

padding: const pw.EdgeInsets.all(10),

decoration: pw.BoxDecoration(

color:

latestScreening?['risk_level']=="Very High"

? PdfColors.red100

:

latestScreening?['risk_level']=="High"

? PdfColors.orange100

:

latestScreening?['risk_level']=="Moderate"

? PdfColors.yellow100

:

PdfColors.green100,

borderRadius:
pw.BorderRadius.circular(10),

),

child: pw.Text(

latestScreening?['risk_level']=="Very High"

? "🔴 Very High Risk"

:

latestScreening?['risk_level']=="High"

? "🟠 High Risk"

:

latestScreening?['risk_level']=="Moderate"

? "🟡 Moderate Risk"

:

"🟢 Normal",

),

),
                pw.SizedBox(height: 15),

                pw.Text(
                  "Average Calories : ${report?['avg_calories']} kcal",
                ),

                pw.Text(
                  "Frequent Food : ${report?['frequent_food']}",
                ),

                pw.Text(
                  "Weight Change : ${report?['weight_change']} kg",
                ),

              ],

            ),

          ),
     

          pw.SizedBox(height: 30),

          // RINGKASAN
          pw.Text(
            "Ringkasan Minggu",
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 10),

          pw.Text(
            report?['report_text'] ?? "",
          ),

          pw.SizedBox(height: 30),

          // RIWAYAT MAKAN
          pw.NewPage(),
          pw.Text(
            "Riwayat Makanan",
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 10),

          pw.TableHelper.fromTextArray(

            headers: [
              "Tanggal",
              "Makanan",
              "Kalori"
            ],

            data: foodHistory.map(
              (food) => [

                food['log_date'],

                food['food_name'],

                "${food['total_calories']}"

              ],
            ).toList(),

          ),

          pw.SizedBox(height: 30),

          // TOP FOOD
          pw.Text(
            "Top Foods",
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          ...topFoods.map(

            (food) => pw.Bullet(

              text:
                  "${food['food_name']} (${food['jumlah']}x)",

            ),

          ),

          pw.SizedBox(height: 30),

          // COACHING
          pw.SizedBox(height:20),

pw.Text(
  "Goal Minggu Depan",
  style: pw.TextStyle(
    fontSize: 20,
    fontWeight: pw.FontWeight.bold,
  ),
),

pw.SizedBox(height:10),

pw.Bullet(
  text: "Catat makanan minimal 5 hari",
),

pw.Bullet(
  text: "Kurangi minuman manis",
),

pw.Bullet(
  text: "Jalan kaki 20 menit setiap hari",
),

pw.Bullet(
  text: "Hindari makan malam terlalu larut",
),
pw.SizedBox(height:20),

pw.Text(
  "AI Recommendation",
  style: pw.TextStyle(
    fontSize: 20,
    fontWeight: pw.FontWeight.bold,
  ),
),

pw.Container(

  padding: const pw.EdgeInsets.all(15),

  decoration: pw.BoxDecoration(
    color: PdfColors.green50,
    borderRadius: pw.BorderRadius.circular(10),
  ),

  child: pw.Text(

    latestScreening?['risk_level']=="Very High"

    ?

    "Kurangi konsumsi makanan tinggi gula dan tingkatkan aktivitas fisik."

    :

    "Pertahankan pola makan sehat dan aktivitas rutin.",

  ),

),
          pw.Text(
            "Weekly Coaching",
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 10),

          pw.Container(

            padding: const pw.EdgeInsets.all(15),

            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: pw.BorderRadius.circular(10),
            ),

            child: pw.Column(

              crossAxisAlignment:
                  pw.CrossAxisAlignment.start,

              children: [

                pw.Text(
                  coaching?['template']['title'] ?? "",
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),

                pw.SizedBox(height: 10),

                pw.Text(
                  coaching?['template']['message'] ?? "",
                ),

              ],

            ),

          ),

          pw.SizedBox(height: 40),

          pw.Divider(),

pw.Center(

child: pw.Column(

children: [

pw.Text(
"Generated by Healthify AI",
),

pw.SizedBox(height:5),

pw.Text(
"This report is intended for educational and lifestyle purposes only.",
),

pw.SizedBox(height:5),

pw.Text(
"© 2026 Healthify",
),

],

),

),
          pw.NewPage(),

pw.Center(

child: pw.Text(

"Health Analytics",

style: pw.TextStyle(

fontSize:26,

fontWeight: pw.FontWeight.bold,

),

),

),

pw.SizedBox(height:20),

pw.Text(
"Weight Progress Chart",
),

pw.SizedBox(height:10),

pw.Container(
  height: 250,
  decoration: pw.BoxDecoration(
    border: pw.Border.all(),
  ),
  child: pw.Center(
    child: pw.Text(
      "Weight Progress Chart",
    ),
  ),
),



pw.SizedBox(height:30),

pw.Text(
"Daily Calories Chart",
),

pw.SizedBox(height:10),

pw.Container(
  height: 250,
  decoration: pw.BoxDecoration(
    border: pw.Border.all(),
  ),
  child: pw.Center(
    child: pw.Text(
      "Daily Calories Chart",
    ),
  ),
),
        ],

      ),

    );

    await Printing.layoutPdf(

      onLayout: (format) async => pdf.save(),

    );
  }
}